/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Recoverable,
  RecoverableInterface,
} from "../../contracts/Recoverable";

const _abi = [
  {
    inputs: [],
    name: "MissingToken",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "UnrecoverableToken",
    type: "error",
  },
] as const;

export class Recoverable__factory {
  static readonly abi = _abi;
  static createInterface(): RecoverableInterface {
    return new utils.Interface(_abi) as RecoverableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Recoverable {
    return new Contract(address, _abi, signerOrProvider) as Recoverable;
  }
}
